/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HoverImage: typeof import('./components/HoverImage.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongListCard: typeof import('./components/SongListCard.vue')['default']
  }
}
